default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: workout_log_development

test:
  <<: *default
  database: workout_log_test

production:
  <<: *default
  database: workout_log_production
  username: workout_log
  password: <%= ENV['WORKOUT_LOG_DATABASE_PASSWORD'] %>
